//比赛筛选action
export const ACTIVE_ALL_FILTER = 'ACTIVE_ALL_FILTER'
export const ACTIVE_A_FILTERS = 'ACTIVE_A_FILTERS'
export const INIT_FILTERS = 'INIT_FILTERS'
export const DISABLE_ALL_FILTER = 'DISABLE_ALL_FILTER'

//比赛目录数据
export const INIT_CATALOG = 'INIT_CATALOG'
export const SWITCH_CATALOG = 'SWITCH_CATALOG'

//比赛列表数据
export const CLIENTLIST_REQUEST = 'CLIENTLIST_REQUEST'
export const CLIENTLIST_SUCCESS = 'CLIENTLIST_SUCCESS'
export const CLIENTLIST_FAILURE = 'CLIENTLIST_FAILURE'


export const DUMPLOG_SUCCESS = 'DUMPLOG_SUCCESS'
export const SET_CURRENT_CLIENT = 'SET_CURRENT_CLIENT'
export const SET_CURRENT_REGION = 'SET_CURRENT_REGION'
